# AUTO-GENERATED by scripts/generate_tool_map.py — DO NOT EDIT BY HAND.
"""Static dispatch table mapping each tool key to the Modal app that serves it."""

from typing import NamedTuple


class ToolEntry(NamedTuple):
    """Where a tool runs, and on what hardware."""

    app: str
    service: str
    method: str
    gpu: bool


TOOL_MAP: dict[str, ToolEntry] = {
    "ablang-embedding": ToolEntry("proto-tools-ablang", "AbLangService", "inference", True),
    "ablang-gradient": ToolEntry("proto-tools-ablang", "AbLangService", "gradient", True),
    "ablang-sample": ToolEntry("proto-tools-ablang", "AbLangService", "sample", True),
    "ablang-score": ToolEntry("proto-tools-ablang", "AbLangService", "score", True),
    "alphafold2-gradient": ToolEntry("proto-tools-alphafold2", "AlphaFold2Service", "gradient", True),
    "alphafold2-prediction": ToolEntry("proto-tools-alphafold2", "AlphaFold2Service", "predict", True),
    "bioemu-sample": ToolEntry("proto-tools-bioemu", "BioEmuService", "sample", True),
    "boltz2-affinity": ToolEntry("proto-tools-boltz2", "Boltz2Service", "affinity", True),
    "boltz2-prediction": ToolEntry("proto-tools-boltz2", "Boltz2Service", "predict", True),
    "borzoi-ensemble": ToolEntry("proto-tools-borzoi", "BorzoiService", "predict_ensemble", True),
    "borzoi-prediction": ToolEntry("proto-tools-borzoi", "BorzoiService", "predict", True),
    "chai1-prediction": ToolEntry("proto-tools-chai1", "Chai1Service", "predict", True),
    "crispr-tracr-rna": ToolEntry("proto-tools-crispr-tracr-rna", "CrisprTracrRNAService", "crispr_tracr_rna", False),
    "dssp-secondary-structure": ToolEntry("proto-tools-dssp", "DSSPService", "compute", False),
    "enformer-prediction": ToolEntry("proto-tools-enformer", "EnformerService", "predict", True),
    "esm-if1-sample": ToolEntry("proto-tools-esmif1", "ESMIF1Service", "sample", True),
    "esm-if1-score": ToolEntry("proto-tools-esmif1", "ESMIF1Service", "score", True),
    "esm2-embedding": ToolEntry("proto-tools-esm2", "ESM2Service", "inference", True),
    "esm2-gradient": ToolEntry("proto-tools-esm2", "ESM2Service", "gradient", True),
    "esm2-sample": ToolEntry("proto-tools-esm2", "ESM2Service", "sample", True),
    "esm2-score": ToolEntry("proto-tools-esm2", "ESM2Service", "score", True),
    "esmc-embedding": ToolEntry("proto-tools-esmc", "ESMCService", "inference", True),
    "esmfold-gradient": ToolEntry("proto-tools-esmfold", "ESMFoldService", "gradient", True),
    "esmfold-prediction": ToolEntry("proto-tools-esmfold", "ESMFoldService", "predict", True),
    "esmfold2-prediction": ToolEntry("proto-tools-esmfold2", "ESMFold2Service", "predict", True),
    "evo1-sample": ToolEntry("proto-tools-evo1", "Evo1Service", "sample", True),
    "evo1-score": ToolEntry("proto-tools-evo1", "Evo1Service", "score", True),
    "evo2-sample": ToolEntry("proto-tools-evo2", "Evo2Service", "sample", True),
    "evo2-score": ToolEntry("proto-tools-evo2", "Evo2Service", "score", True),
    "fampnn-pack": ToolEntry("proto-tools-fampnn", "FAMPNNService", "pack", True),
    "fampnn-sample": ToolEntry("proto-tools-fampnn", "FAMPNNService", "sample", True),
    "fampnn-score": ToolEntry("proto-tools-fampnn", "FAMPNNService", "score", True),
    "fampnn-score-all-mutations": ToolEntry("proto-tools-fampnn", "FAMPNNService", "score_all_mutations", True),
    "freebindcraft-design": ToolEntry("proto-tools-freebindcraft", "FreeBindCraftService", "design", True),
    "ipsae-scoring": ToolEntry("proto-tools-ipsae", "IPSAEService", "score", False),
    "ligandmpnn-sample": ToolEntry("proto-tools-ligandmpnn", "LigandMPNNService", "sample", True),
    "ligandmpnn-score": ToolEntry("proto-tools-ligandmpnn", "LigandMPNNService", "score", True),
    "mafft-align": ToolEntry("proto-tools-mafft", "MafftAlignService", "align", False),
    "malinois-gradient": ToolEntry("proto-tools-malinois", "MalinoisService", "gradient", True),
    "malinois-score": ToolEntry("proto-tools-malinois", "MalinoisService", "score", True),
    "metal3d-prediction": ToolEntry("proto-tools-metal3d", "Metal3DService", "predict", True),
    "minced-crispr": ToolEntry("proto-tools-minced", "MincedService", "detect", False),
    "orfipy-prediction": ToolEntry("proto-tools-orfipy", "OrfipyService", "predict", False),
    "pangolin-predict": ToolEntry("proto-tools-pangolin", "PangolinService", "predict", True),
    "pangolin-score-variants": ToolEntry("proto-tools-pangolin", "PangolinService", "score_variants", True),
    "progen2-sample": ToolEntry("proto-tools-progen2", "ProGen2Service", "sample", True),
    "progen2-score": ToolEntry("proto-tools-progen2", "ProGen2Service", "score", True),
    "proteinmpnn-gradient": ToolEntry("proto-tools-proteinmpnn", "ProteinMPNNService", "gradient", True),
    "proteinmpnn-sample": ToolEntry("proto-tools-proteinmpnn", "ProteinMPNNService", "sample", True),
    "proteinmpnn-score": ToolEntry("proto-tools-proteinmpnn", "ProteinMPNNService", "score", True),
    "protenix-prediction": ToolEntry("proto-tools-protenix", "ProtenixService", "predict", True),
    "pymol-rmsd-alignment": ToolEntry("proto-tools-pymol", "PyMOLService", "align", False),
    "rf3-prediction": ToolEntry("proto-tools-rf3", "RF3Service", "predict", True),
    "rfdiffusion3-design": ToolEntry("proto-tools-rfdiffusion3", "RFdiffusion3Service", "generate", True),
    "segmasker-score": ToolEntry("proto-tools-segmasker", "SegmaskerService", "score", False),
    "splice-transformer-prediction": ToolEntry("proto-tools-splice-transformer", "SpliceTransformerService", "run", True),
    "tmalign-alignment": ToolEntry("proto-tools-tmalign", "TMalignService", "align", False),
    "usalign-alignment": ToolEntry("proto-tools-usalign", "USalignService", "align", False),
}
