#!/usr/bin/env python
"""Regenerate ``proto_tools/modal/tool_map.py``. Run after editing the manifest.

The map is the static ``tool_key → (app, service, method, gpu)`` table a client
dispatches through. It has to be a committed file because a client reads it at
runtime, and reading it is what lets a client avoid importing the service
modules -- which would construct every ``modal.Image`` chain just to answer a
question about one tool.

Deploy entrypoints are not generated here. ``deploy.py`` renders one into a
scratch directory per deploy, so it cannot drift from the manifest and adding a
service of your own writes nothing into your tree.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

TOOL_MAP_PATH = REPO / "proto_tools" / "modal" / "tool_map.py"

__all__ = ["TOOL_MAP_PATH", "render_tool_map"]


HEADER = "# AUTO-GENERATED by scripts/generate_tool_map.py — DO NOT EDIT BY HAND."


def render_tool_map() -> str:
    """Render the static dispatch table.

    Importing every service is what populates the registry. That is expensive --
    it constructs each image chain -- which is why the result is written to a file
    for clients to read instead.
    """
    from proto_tools.modal.manifest import GPU_SERVICES, get_app_name_for_service
    from proto_tools.modal.registry import get_registry, import_all_services

    import_all_services()

    rows = []
    for key, (service, method) in sorted(get_registry().items()):
        app = get_app_name_for_service(service)
        rows.append(f'    "{key}": ToolEntry("{app}", "{service}", "{method}", {service in GPU_SERVICES}),')

    return (
        f"{HEADER}\n"
        '"""Static dispatch table mapping each tool key to the Modal app that serves it."""\n'
        "\n"
        "from typing import NamedTuple\n"
        "\n"
        "\n"
        "class ToolEntry(NamedTuple):\n"
        '    """Where a tool runs, and on what hardware."""\n'
        "\n"
        "    app: str\n"
        "    service: str\n"
        "    method: str\n"
        "    gpu: bool\n"
        "\n"
        "\n"
        "TOOL_MAP: dict[str, ToolEntry] = {\n" + "\n".join(rows) + "\n}\n"
    )


def main() -> None:
    """Write the tool map and report whether it changed."""
    from proto_tools.modal.manifest import APP_BUCKETS

    source = render_tool_map()
    if TOOL_MAP_PATH.exists() and TOOL_MAP_PATH.read_text() == source:
        print(f"{len(APP_BUCKETS)} app(s); tool map already current")
        return

    TOOL_MAP_PATH.write_text(source)
    print(f"  wrote {TOOL_MAP_PATH.relative_to(REPO)}")
    print(f"{len(APP_BUCKETS)} app(s); 1 file updated")


if __name__ == "__main__":
    main()
