"""Masked language models for protein sequence editing."""

from proto_tools.tools.masked_models.ablang import (
    AbLangEmbeddingsConfig,
    AbLangEmbeddingsInput,
    AbLangEmbeddingsOutput,
    AbLangGradientConfig,
    AbLangGradientInput,
    AbLangGradientOutput,
    AbLangSampleConfig,
    AbLangSampleInput,
    AbLangSampleOutput,
    AbLangScoringConfig,
    AbLangScoringInput,
    AbLangScoringOutput,
    run_ablang_embeddings,
    run_ablang_gradient,
    run_ablang_sample,
    run_ablang_score,
)
from proto_tools.tools.masked_models.codonfm import (
    CODONFM_CHECKPOINTS,
    CODONFM_CODON_VOCAB,
    CODONFM_NUM_CODONS,
    CodonFMCheckpoint,
    CodonFMConfig,
    CodonFMEmbeddingResult,
    CodonFMEmbeddingsConfig,
    CodonFMEmbeddingsInput,
    CodonFMEmbeddingsOutput,
    CodonFMFitnessConfig,
    CodonFMFitnessInput,
    CodonFMFitnessOutput,
    CodonFMFitnessResult,
    CodonFMGradientConfig,
    CodonFMGradientInput,
    CodonFMGradientOutput,
    CodonFMMutation,
    CodonFMMutationResult,
    CodonFMSampleConfig,
    CodonFMSampleInput,
    CodonFMSampleOutput,
    CodonFMSampleResult,
    CodonFMScoreConfig,
    CodonFMScoreInput,
    CodonFMScoreOutput,
    CodonSequenceInput,
    normalize_codon_sequence,
    one_hot_codon_logits,
    resolve_checkpoint_source,
    run_codonfm_embeddings,
    run_codonfm_fitness,
    run_codonfm_gradient,
    run_codonfm_sample,
    run_codonfm_score,
)
from proto_tools.tools.masked_models.esm2 import (
    ESM2EmbeddingsConfig,
    ESM2EmbeddingsInput,
    ESM2EmbeddingsOutput,
    ESM2GradientConfig,
    ESM2GradientInput,
    ESM2GradientOutput,
    ESM2SampleConfig,
    ESM2SampleInput,
    ESM2SampleOutput,
    ESM2ScoringConfig,
    ESM2ScoringInput,
    ESM2ScoringOutput,
    run_esm2_embeddings,
    run_esm2_gradient,
    run_esm2_sample,
    run_esm2_score,
)
from proto_tools.tools.masked_models.esm3 import (
    ESM3EmbeddingsConfig,
    ESM3EmbeddingsInput,
    ESM3EmbeddingsOutput,
    ESM3SampleConfig,
    ESM3SampleInput,
    ESM3SampleOutput,
    ESM3ScoringConfig,
    ESM3ScoringInput,
    ESM3ScoringOutput,
    run_esm3_embeddings,
    run_esm3_sample,
    run_esm3_score,
)
from proto_tools.tools.masked_models.esmc import (
    ESMCEmbeddingsConfig,
    ESMCEmbeddingsInput,
    ESMCEmbeddingsOutput,
    run_esmc_embeddings,
)
from proto_tools.tools.masked_models.shared_data_models import (
    MaskedModelEmbeddingsConfig,
    MaskedModelEmbeddingsOutput,
    MaskedModelSampleConfig,
    MaskedModelSampleOutput,
    MaskedModelScoringConfig,
    MaskedModelScoringMetrics,
    MaskedModelScoringOutput,
    Projection2D,
    SequenceEmbedding,
)
from proto_tools.transforms.masking import MaskingMethod, MaskingStrategy

__all__ = [
    # Masking strategies
    "MaskingStrategy",
    "MaskingMethod",
    # Shared data models
    "MaskedModelEmbeddingsConfig",
    "MaskedModelEmbeddingsOutput",
    "MaskedModelSampleConfig",
    "MaskedModelSampleOutput",
    "MaskedModelScoringConfig",
    "MaskedModelScoringMetrics",
    "MaskedModelScoringOutput",
    "Projection2D",
    "SequenceEmbedding",
    # AbLang - Embeddings
    "AbLangEmbeddingsConfig",
    "AbLangEmbeddingsInput",
    "AbLangEmbeddingsOutput",
    "run_ablang_embeddings",
    # AbLang - Gradient
    "AbLangGradientConfig",
    "AbLangGradientInput",
    "AbLangGradientOutput",
    "run_ablang_gradient",
    # AbLang - Sampling
    "AbLangSampleConfig",
    "AbLangSampleInput",
    "AbLangSampleOutput",
    "run_ablang_sample",
    # AbLang - Scoring
    "AbLangScoringConfig",
    "AbLangScoringInput",
    "AbLangScoringOutput",
    "run_ablang_score",
    # CodonFM - shared
    "CODONFM_CHECKPOINTS",
    "CODONFM_CODON_VOCAB",
    "CODONFM_NUM_CODONS",
    "CodonFMCheckpoint",
    "CodonFMConfig",
    "CodonSequenceInput",
    "normalize_codon_sequence",
    "one_hot_codon_logits",
    "resolve_checkpoint_source",
    # CodonFM - Fitness
    "CodonFMFitnessConfig",
    "CodonFMFitnessInput",
    "CodonFMFitnessOutput",
    "CodonFMFitnessResult",
    "run_codonfm_fitness",
    # CodonFM - Embeddings
    "CodonFMEmbeddingResult",
    "CodonFMEmbeddingsConfig",
    "CodonFMEmbeddingsInput",
    "CodonFMEmbeddingsOutput",
    "run_codonfm_embeddings",
    # CodonFM - Scoring
    "CodonFMMutation",
    "CodonFMMutationResult",
    "CodonFMScoreConfig",
    "CodonFMScoreInput",
    "CodonFMScoreOutput",
    "run_codonfm_score",
    # CodonFM - Gradient
    "CodonFMGradientConfig",
    "CodonFMGradientInput",
    "CodonFMGradientOutput",
    "run_codonfm_gradient",
    # CodonFM - Sampling
    "CodonFMSampleConfig",
    "CodonFMSampleInput",
    "CodonFMSampleOutput",
    "CodonFMSampleResult",
    "run_codonfm_sample",
    # ESM2 - Embeddings
    "run_esm2_embeddings",
    "ESM2EmbeddingsInput",
    "ESM2EmbeddingsConfig",
    "ESM2EmbeddingsOutput",
    # ESM2 - Gradient
    "run_esm2_gradient",
    "ESM2GradientInput",
    "ESM2GradientConfig",
    "ESM2GradientOutput",
    # ESM2 - Sampling
    "run_esm2_sample",
    "ESM2SampleInput",
    "ESM2SampleConfig",
    "ESM2SampleOutput",
    # ESM2 - Scoring
    "run_esm2_score",
    "ESM2ScoringInput",
    "ESM2ScoringConfig",
    "ESM2ScoringOutput",
    # ESM3 - Embeddings
    "run_esm3_embeddings",
    "ESM3EmbeddingsInput",
    "ESM3EmbeddingsConfig",
    "ESM3EmbeddingsOutput",
    # ESM3 - Sampling
    "run_esm3_sample",
    "ESM3SampleInput",
    "ESM3SampleConfig",
    "ESM3SampleOutput",
    # ESM3 - Scoring
    "run_esm3_score",
    "ESM3ScoringInput",
    "ESM3ScoringConfig",
    "ESM3ScoringOutput",
    # ESM C - Embeddings
    "run_esmc_embeddings",
    "ESMCEmbeddingsInput",
    "ESMCEmbeddingsConfig",
    "ESMCEmbeddingsOutput",
]
